
export const original_foods = [
    { id: "1", name: "Greek salad", price: 12, description: "Food provides essential nutrients for overall health and well-being", category: "Salad", calories: 150, protein: 5, carbs: 10, fats: 8 },
    { id: "2", name: "Veg salad", price: 18, description: "Food provides essential nutrients for overall health and well-being", category: "Salad", calories: 120, protein: 3, carbs: 15, fats: 5 },
    { id: "3", name: "Clover Salad", price: 16, description: "Food provides essential nutrients for overall health and well-being", category: "Salad", calories: 130, protein: 4, carbs: 12, fats: 6 },
    { id: "4", name: "Chicken Salad", price: 24, description: "Food provides essential nutrients for overall health and well-being", category: "Salad", calories: 250, protein: 20, carbs: 5, fats: 10 },
    { id: "5", name: "Lasagna Rolls", price: 14, description: "Food provides essential nutrients for overall health and well-being", category: "Rolls", calories: 400, protein: 15, carbs: 35, fats: 18 },
    { id: "6", name: "Peri Peri Rolls", price: 12, description: "Food provides essential nutrients for overall health and well-being", category: "Rolls", calories: 350, protein: 12, carbs: 30, fats: 15 },
    { id: "7", name: "Chicken Rolls", price: 20, description: "Food provides essential nutrients for overall health and well-being", category: "Rolls", calories: 380, protein: 18, carbs: 25, fats: 16 },
    { id: "8", name: "Veg Rolls", price: 15, description: "Food provides essential nutrients for overall health and well-being", category: "Rolls", calories: 300, protein: 8, carbs: 35, fats: 12 },
    { id: "9", name: "Ripple Ice Cream", price: 14, description: "Food provides essential nutrients for overall health and well-being", category: "Desserts", calories: 220, protein: 4, carbs: 25, fats: 10 },
    { id: "10", name: "Fruit Ice Cream", price: 22, description: "Food provides essential nutrients for overall health and well-being", category: "Desserts", calories: 200, protein: 3, carbs: 30, fats: 8 },
    { id: "11", name: "Jar Ice Cream", price: 10, description: "Food provides essential nutrients for overall health and well-being", category: "Desserts", calories: 250, protein: 5, carbs: 28, fats: 12 },
    { id: "12", name: "Vanilla Ice Cream", price: 12, description: "Food provides essential nutrients for overall health and well-being", category: "Desserts", calories: 180, protein: 4, carbs: 22, fats: 9 },
    { id: "13", name: "Chicken Sandwich", price: 12, description: "Food provides essential nutrients for overall health and well-being", category: "Sandwich", calories: 350, protein: 25, carbs: 30, fats: 15 },
    { id: "14", name: "Vegan Sandwich", price: 18, description: "Food provides essential nutrients for overall health and well-being", category: "Sandwich", calories: 280, protein: 12, carbs: 35, fats: 10 },
    { id: "15", name: "Grilled Sandwich", price: 16, description: "Food provides essential nutrients for overall health and well-being", category: "Sandwich", calories: 320, protein: 15, carbs: 30, fats: 14 },
    { id: "16", name: "Bread Sandwich", price: 24, description: "Food provides essential nutrients for overall health and well-being", category: "Sandwich", calories: 300, protein: 10, carbs: 40, fats: 12 },
    { id: "17", name: "Cup Cake", price: 14, description: "Food provides essential nutrients for overall health and well-being", category: "Cake", calories: 250, protein: 4, carbs: 35, fats: 12 },
    { id: "18", name: "Vegan Cake", price: 12, description: "Food provides essential nutrients for overall health and well-being", category: "Cake", calories: 220, protein: 3, carbs: 38, fats: 10 },
    { id: "19", name: "Butterscotch Cake", price: 20, description: "Food provides essential nutrients for overall health and well-being", category: "Cake", calories: 300, protein: 5, carbs: 40, fats: 14 },
    { id: "20", name: "Sliced Cake", price: 15, description: "Food provides essential nutrients for overall health and well-being", category: "Cake", calories: 280, protein: 4, carbs: 35, fats: 12 },
    { id: "21", name: "Garlic Mushroom", price: 14, description: "Food provides essential nutrients for overall health and well-being", category: "Pure Veg", calories: 150, protein: 6, carbs: 10, fats: 8 },
    { id: "22", name: "Fried Cauliflower", price: 22, description: "Food provides essential nutrients for overall health and well-being", category: "Pure Veg", calories: 180, protein: 4, carbs: 15, fats: 11 },
    { id: "23", name: "Mix Veg Pulao", price: 10, description: "Food provides essential nutrients for overall health and well-being", category: "Pure Veg", calories: 350, protein: 8, carbs: 60, fats: 10 },
    { id: "24", name: "Rice Zucchini", price: 12, description: "Food provides essential nutrients for overall health and well-being", category: "Pure Veg", calories: 320, protein: 7, carbs: 55, fats: 9 },
    { id: "25", name: "Cheese Pasta", price: 12, description: "Food provides essential nutrients for overall health and well-being", category: "Pasta", calories: 450, protein: 15, carbs: 50, fats: 20 },
    { id: "26", name: "Tomato Pasta", price: 18, description: "Food provides essential nutrients for overall health and well-being", category: "Pasta", calories: 400, protein: 12, carbs: 55, fats: 15 },
    { id: "27", name: "Creamy Pasta", price: 16, description: "Food provides essential nutrients for overall health and well-being", category: "Pasta", calories: 500, protein: 14, carbs: 45, fats: 30 },
    { id: "28", name: "Chicken Pasta", price: 24, description: "Food provides essential nutrients for overall health and well-being", category: "Pasta", calories: 550, protein: 25, carbs: 50, fats: 25 },
    { id: "29", name: "Buttter Noodles", price: 14, description: "Food provides essential nutrients for overall health and well-being", category: "Noodles", calories: 380, protein: 8, carbs: 50, fats: 16 },
    { id: "30", name: "Veg Noodles", price: 12, description: "Food provides essential nutrients for overall health and well-being", category: "Noodles", calories: 350, protein: 7, carbs: 55, fats: 12 },
    { id: "31", name: "Somen Noodles", price: 20, description: "Food provides essential nutrients for overall health and well-being", category: "Noodles", calories: 320, protein: 9, carbs: 45, fats: 10 },
    { id: "32", name: "Cooked Noodles", price: 15, description: "Food provides essential nutrients for overall health and well-being", category: "Noodles", calories: 340, protein: 8, carbs: 50, fats: 11 }
];
